from django.db import models


class Ticker(models.Model):
    objects = models.Manager()

    table = models.CharField(max_length=10, null=False)
    permaticker = models.IntegerField(primary_key=True)
    ticker = models.CharField(max_length=10, null=False)
    name = models.CharField(max_length=100, null=False)
    exchange = models.CharField(max_length=100, null=False)
    isdelisted = models.CharField(max_length=1, null=False)
    category = models.CharField(max_length=100, null=False)
    cusips = models.CharField(max_length=100, null=True)
    siccode = models.CharField(max_length=100, null=True)
    sicsector = models.CharField(max_length=100, null=True)
    sicindustry = models.CharField(max_length=100, null=True)
    famasector = models.CharField(max_length=100, null=True)
    famaindustry = models.CharField(max_length=100, null=True)
    sector = models.CharField(max_length=100, null=True)
    industry = models.CharField(max_length=100, null=True)
    scalemarketcap = models.CharField(max_length=100, null=True)
    scalerevenue = models.CharField(max_length=100, null=True)
    relatedtickers = models.CharField(max_length=100, null=True)
    currency = models.CharField(max_length=100, null=True)
    location = models.CharField(max_length=100, null=True)
    lastupdated = models.CharField(max_length=100, null=True)
    firstadded = models.CharField(max_length=100, null=False)
    firstpricedate = models.CharField(max_length=100, null=False)
    lastpricedate = models.CharField(max_length=100, null=False)
    firstquarter = models.CharField(max_length=100, null=False)
    lastquarter = models.CharField(max_length=100, null=False)
    secfilings = models.CharField(max_length=100, null=False)
    companysite = models.CharField(max_length=100, null=True)
