# Generated by Django 2.2 on 2019-10-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("equities", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="table",
            field=models.CharField(choices=[("SF1", "SF1")], max_length=10),
        )
    ]
