# Generated by Django 2.2 on 2019-10-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("equities", "0003_auto_20191005_2302")]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="famasector",
            field=models.CharField(max_length=100, null=True),
        )
    ]
