# Generated by Django 2.2 on 2019-10-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("equities", "0006_auto_20191005_2303")]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="relatedtickers",
            field=models.CharField(max_length=100, null=True),
        )
    ]
