# Generated by Django 2.2 on 2019-10-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("equities", "0008_auto_20191005_2303")]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="currency",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="famaindustry",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="industry",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="lastupdated",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="sector",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="siccode",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="sicindustry",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="sicsector",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
